name: 'Setup Java5'
GITHUB_TOKEN: ${{ secrets.ALEX_REPO_TOKEN }}
description: 'Install Java 5 & Ant'
inputs:
  path-java:
    description: 'Path  of Java5'
    required: true
    default: '/'

  path-token:
    description: 'Token'
    required: true
    default: '-'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          clean: false  # This is required to keep the build files

    - name: Download java via curl
      run: | 
        curl -L -O -H "Accept: application/vnd.github+json" -H "Authorization: Bearer  ${{ inputs.path-token}}" -H "X-GitHub-Api-Version: 2022-11-28" https://raw.githubusercontent.com/AlexRodriguez09/setup-java-1.5/main/jdk-1_5_0_12-linux-amd64.bin
        ls -la 
      shell: bash

    - name: Install Java 5
      run: |
        ls -la
        echo Running install java 5
        echo Started on `date`
        sudo mkdir /usr/lib/jvm/java5
        sudo cp ${{ inputs.path-java}} /usr/lib/jvm/java5/jdk-1_5_0_12-linux-amd64.bin
        sudo chmod a+x /usr/lib/jvm/java5/jdk-1_5_0_12-linux-amd64.bin
        sudo chown -R root:root /usr/lib/jvm/java5/
        echo "Print folder"
        ls -la /usr/lib/jvm/
        cd /usr/lib/jvm/java5/
        sudo echo "yes" | sudo ./jdk-1_5_0_12-linux-amd64.bin

        sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/java5/jdk1.5.0_12/bin/java" 1
        sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/java5/jdk1.5.0_12/bin/javac" 1

        sudo update-alternatives --set java /usr/lib/jvm/java5/jdk1.5.0_12/bin/java
        sudo update-alternatives --set javac /usr/lib/jvm/java5/jdk1.5.0_12/bin/javac

        sudo chmod a+x /usr/bin/java
        sudo chmod a+x /usr/bin/javac

        sudo chown -R root:root /usr/lib/jvm/java5/
        echo $JAVA_HOME
        export JAVA_HOME=/usr/lib/jvm/java5/jdk1.5.0_12
        echo $JAVA_HOME
        echo $PATH
        export PATH=$JAVA_HOME/bin:$PATH
        echo "PATH changed"
        echo $PATH
        echo "java version"
        java -version
        echo Done on `date`
      shell: bash