name: Security Interface yml

on: workflow_call

jobs:
  download-bins:
    name: 'Upload ant - java'
    runs-on: ubuntu-latest
  
    steps:
  
      - name: Checkout
        uses: actions/checkout@v3
        with:
            clean: false  # This is required to keep the build files

      
      - name: Creating folder
        run: |
          sudo mkdir ${{ github.workspace }}/installers
          sudo cp ${{ github.workspace }}/apache-ant-1.7.1-bin.tar.gz ${{ github.workspace }}/installers
          sudo cp ${{ github.workspace }}/jdk-1_5_0_12-linux-amd64.bin ${{ github.workspace }}/installers

      - name: Upload bins
        uses: actions/upload-artifact@v3
        with:
          name: security-common
          path: ${{ github.workspace }}/deploy-artifacts/lib-common/